### create method

POST http://localhost:8080/api/tasks 
Content-Type: application/json

{
    "title": "teste",
    "description": "testeeee",
    "priority": 1
}

### get all method

GET http://localhost:8080/api/tasks

### get by id method

GET http://localhost:8080/api/tasks/1

### update method

PUT http://localhost:8080/api/tasks/1 
Content-Type: application/json

{
    "title": "Updated Todo",
    "description": "This is an updated todo item",
    "completed": true,
    "priority": 2
}

### delete method

DELETE http://localhost:8080/api/tasks/1